image: node:14.4.0

services:
  - docker:19.03.12-dind

stages:
  - deploy
  - build

cache:
  paths:
  - node_modules/
  - .yarn

build:
  stage: build
 # only: 
 #   - master
  when: manual
  script:
    - export CI=false
    - npm install
    - make build
    - make push

deploy:
  stage: deploy
  when: manual
  script:
    - npm i -g firebase-tools
    - export CI=false
    - yarn install
    - yarn deploy
