image: node:14.4.0

stages:
  - deploy
  - build

cache:
  paths:
  - node_modules/
  - .yarn

build:
  only: 
    - master
  script:
    - npm install
    - make build
    - make push

deploy:
  only: 
    - development
  script:
    - npm i -g firebase-tools
    - export CI=false
    - yarn install
    - yarn deploy
